### ISSUE TITLE
login-layout

### ISSUE THREAD

**Issue by Torehpies** [Torehpies/kowtsi2#2]
Figma link: https://www.figma.com/file/IvZzM1TXnYfPfcIb61Z3e8/kowtsi2?type=design&node-id=17-63&mode=design

**Comment by mawrk19** [comment]
nigagawa na

**Comment by Torehpies** [comment]
Figma link
[https://www.figma.com/file/IvZzM1TXnYfPfcIb61Z3e8/kowtsi2?type=design&node-id=17-63&mode=design](url)
